# Copyright 2018 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.!

"""Maps the "third_party/absl/..." include paths to the abseil-cpp module.

The SentencePiece sources include Abseil headers with a "third_party/absl/"
prefix. The CMake build satisfies those includes by symlinking
third_party/absl to the abseil-cpp checkout. For Bazel, the repository rule
below generates a small repository of forwarding headers, one per Abseil
header used by the sources, each of which simply includes the corresponding
"absl/..." header from the abseil-cpp module fetched from the Bazel Central
Registry. No Abseil code is vendored or duplicated.

Keep _ABSL_HEADERS in sync with the "third_party/absl/..." includes used by
the sources, and the deps of //bazel:absl in sync with the Abseil targets
that provide them. A missing entry shows up as a "file not found" error for
the corresponding include.
"""

_ABSL_HEADERS = [
    "base/attributes.h",
    "base/internal/endian.h",
    "base/thread_annotations.h",
    "cleanup/cleanup.h",
    "container/btree_set.h",
    "container/fixed_array.h",
    "container/flat_hash_map.h",
    "container/flat_hash_set.h",
    "flags/flag.h",
    "flags/parse.h",
    "flags/usage.h",
    "flags/usage_config.h",
    "functional/any_invocable.h",
    "functional/function_ref.h",
    "hash/hash.h",
    "log/check.h",
    "log/flags.h",
    "log/globals.h",
    "log/initialize.h",
    "log/log.h",
    "numeric/bits.h",
    "random/random.h",
    "status/status.h",
    "status/status_builder.h",
    "status/status_macros.h",
    "strings/ascii.h",
    "strings/match.h",
    "strings/numbers.h",
    "strings/str_cat.h",
    "strings/str_format.h",
    "strings/str_join.h",
    "strings/str_replace.h",
    "strings/str_split.h",
    "strings/string_view.h",
    "strings/strip.h",
    "synchronization/blocking_counter.h",
    "synchronization/mutex.h",
    "time/clock.h",
    "time/time.h",
    "types/span.h",
]

_HEADER_TEMPLATE = """\
// Generated by //bazel:absl_compat.bzl. Forwards the
// "third_party/absl/{header}" include path used by the SentencePiece
// sources to the abseil-cpp Bazel module.
#ifndef {guard}
#define {guard}

#include "absl/{header}"

#endif  // {guard}
"""

_BUILD_TEMPLATE = """\
# Generated by //bazel:absl_compat.bzl.

load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "headers",
    hdrs = [
{hdrs}
    ],
)
"""

def _absl_include_compat_impl(repository_ctx):
    hdrs = []
    for header in repository_ctx.attr.headers:
        guard = "SENTENCEPIECE_ABSL_COMPAT_%s_" % (
            header.replace("/", "_").replace(".", "_").upper()
        )
        repository_ctx.file(
            "third_party/absl/" + header,
            _HEADER_TEMPLATE.format(header = header, guard = guard),
        )
        hdrs.append('        "third_party/absl/%s",' % header)
    repository_ctx.file(
        "BUILD.bazel",
        _BUILD_TEMPLATE.format(hdrs = "\n".join(hdrs)),
    )

absl_include_compat = repository_rule(
    implementation = _absl_include_compat_impl,
    attrs = {
        "headers": attr.string_list(default = _ABSL_HEADERS),
    },
    doc = "Generates third_party/absl/... forwarding headers for abseil-cpp.",
)
